"""Core contracts for the provider scaffold."""

from .catalog import (
    ModelCatalog,
    build_live_model_catalog,
    build_live_model_catalog_from_models,
)
from .chat import (
    build_openai_chat_completion_response,
    normalize_openai_chat_request,
    render_prompt,
)
from .errors import (
    ErrorDetail,
    ErrorResponse,
    ProviderError,
    install_error_handlers,
)
from .models import (
    AnthropicCountTokensResponse,
    AnthropicMessageResponse,
    AnthropicMessagesCountTokensRequest,
    AnthropicMessagesCreateRequest,
    AnthropicModelInfo,
    AnthropicModelListResponse,
    AnthropicUsage,
    CanonicalChatMessage,
    CanonicalChatRequest,
    CopilotModelBilling,
    CopilotModelCapabilities,
    CopilotModelLimits,
    CopilotModelMetadata,
    CopilotModelPolicy,
    CopilotModelSupports,
    CopilotModelVisionLimits,
    InternalHealthResponse,
    ModelCatalogEntry,
    OpenAIChatCompletionChoice,
    OpenAIChatCompletionRequest,
    OpenAIChatCompletionResponse,
    OpenAIChatMessage,
    OpenAIModelCard,
    OpenAIModelListResponse,
    OpenAIUsage,
    ResolvedRoute,
    RuntimeCompletion,
    RuntimeDiscoveredModel,
    RuntimeHealth,
)
from .routing import ModelRouter, ModelRouterProtocol

__all__ = [
    'AnthropicCountTokensResponse',
    'AnthropicMessageResponse',
    'AnthropicMessagesCountTokensRequest',
    'AnthropicMessagesCreateRequest',
    'AnthropicModelInfo',
    'AnthropicModelListResponse',
    'AnthropicUsage',
    'CanonicalChatMessage',
    'CanonicalChatRequest',
    'CopilotModelBilling',
    'CopilotModelCapabilities',
    'CopilotModelLimits',
    'CopilotModelMetadata',
    'CopilotModelPolicy',
    'CopilotModelSupports',
    'CopilotModelVisionLimits',
    'ErrorDetail',
    'ErrorResponse',
    'InternalHealthResponse',
    'ModelCatalog',
    'ModelCatalogEntry',
    'ModelRouter',
    'ModelRouterProtocol',
    'OpenAIChatCompletionChoice',
    'OpenAIChatCompletionRequest',
    'OpenAIChatCompletionResponse',
    'OpenAIChatMessage',
    'OpenAIModelCard',
    'OpenAIModelListResponse',
    'OpenAIUsage',
    'ProviderError',
    'ResolvedRoute',
    'RuntimeCompletion',
    'RuntimeDiscoveredModel',
    'RuntimeHealth',
    'build_live_model_catalog',
    'build_live_model_catalog_from_models',
    'build_openai_chat_completion_response',
    'install_error_handlers',
    'normalize_openai_chat_request',
    'render_prompt',
]
